name: money_trace
description: "A Flutter project for expense tracking"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^14.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
